import {
  Accessibility,
  BadgeCheck,
  Baby,
  Banknote,
  Bike,
  Briefcase,
  BriefcaseBusiness,
  Building2,
  BusFront,
  CalendarCheck,
  Car,
  CircleHelp,
  ClipboardList,
  Coins,
  CreditCard,
  Crown,
  FileSignature,
  FileText,
  FolderDown,
  Gift,
  Globe,
  GraduationCap,
  Handshake,
  Headset,
  HeartPulse,
  House,
  IdCard,
  Key,
  Landmark,
  Mail,
  MessageCircleQuestion,
  MessageSquareWarning,
  Motorbike,
  Package,
  PersonStanding,
  Phone,
  Plane,
  Receipt,
  RefreshCw,
  Scale,
  ShieldCheck,
  Siren,
  Stethoscope,
  Truck,
  UserRound,
  Users,
  Van,
  Wallet,
  Wrench,
  type LucideIcon,
} from "lucide-react";

/**
 * Curated icon set for visit reasons and priority lanes. Bundled statically (no runtime fetch) so kiosks and
 * displays work offline. Keys are stored in the database.
 */
export const ENTITY_ICONS: Record<string, LucideIcon> = {
  "message-circle-question": MessageCircleQuestion,
  "file-signature": FileSignature,
  "message-square-warning": MessageSquareWarning,
  "folder-down": FolderDown,
  "briefcase-business": BriefcaseBusiness,
  briefcase: Briefcase,
  "refresh-cw": RefreshCw,
  "credit-card": CreditCard,
  landmark: Landmark,
  receipt: Receipt,
  "file-text": FileText,
  "id-card": IdCard,
  users: Users,
  "user-round": UserRound,
  "building-2": Building2,
  handshake: Handshake,
  wrench: Wrench,
  headset: Headset,
  package: Package,
  truck: Truck,
  stethoscope: Stethoscope,
  scale: Scale,
  "graduation-cap": GraduationCap,
  car: Car,
  motorbike: Motorbike,
  van: Van,
  bike: Bike,
  "bus-front": BusFront,
  house: House,
  banknote: Banknote,
  wallet: Wallet,
  "shield-check": ShieldCheck,
  "clipboard-list": ClipboardList,
  "calendar-check": CalendarCheck,
  phone: Phone,
  mail: Mail,
  gift: Gift,
  globe: Globe,
  plane: Plane,
  "heart-pulse": HeartPulse,
  coins: Coins,
  key: Key,
  "badge-check": BadgeCheck,
  crown: Crown,
  accessibility: Accessibility,
  baby: Baby,
  "person-standing": PersonStanding,
  siren: Siren,
  "circle-help": CircleHelp,
};

export const ENTITY_ICON_KEYS = Object.keys(ENTITY_ICONS);

export function EntityIcon({ name, className }: { name: string | null | undefined; className?: string }) {
  const Icon = (name && ENTITY_ICONS[name]) || CircleHelp;
  return <Icon className={className} aria-hidden />;
}
